trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    python38:
      python.version: "3.8"
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "use Python $(python.version)"
  - script: |
      python -m pip install --upgrade pip 
      pip install virtualenv 
      virtualenv .venv 
      source .venv/bin/activate
      pip install pytest build
    displayName: "upgrade pip and activate venv"
  - script: |
      pytest
    displayName: "testing the package"
